version: "3.8"
services:
  app:
    container_name: cafeteria-event
    entrypoint:
    - sleep
    - infinity
    image: docker/dev-environments-java:stable-1
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
volumes:
  app: