FROM openjdk:18 AS JAVA_18
FROM gradle:7.5.1 AS BUILD_STAGE
ENV APP_HOME=/usr/app

RUN mkdir $APP_HOME

WORKDIR $APP_HOME

COPY . $APP_HOME
RUN gradle clean build
ENV EXECUTABLE=$APP_HOME/build/libs/cafeteria-event-0.0.1-SNAPSHOT.jar
ENTRYPOINT java -jar $EXECUTABLE

EXPOSE 8080

